# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  config.vm.box = "centos/7"
  
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox", mount_options: ["dmode=755,fmode=775"]

  config.ssh.insert_key = false

  config.vm.define "devbox" do |node|
    node.vm.hostname = "devbox"
    node.vm.network "public_network"
  end


  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.provision "shell", path: "provisioners/yum_install.sh"

  config.vm.provision "shell", path: "provisioners/pip_install.sh"


end
