# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  # if Vagrant.has_plugin?("vagrant-vbguest")
  #   config.vbguest.auto_update = false
  # end

  config.vm.box = "centos/7"
  
  # do not use the synced folder at this layer. It might fail, but in the next layer it won't
  # config.vm.synced_folder ".", "/vagrant", type: "virtualbox", mount_options: ["dmode=755,fmode=775"]

  config.ssh.insert_key = false

  config.vm.define "devbox" do |node|
    node.vm.hostname = "devbox"
    node.vm.network "public_network"
  end

  # config.vm.provider "virtualbox" do |vb|
  #   vb.memory = "1024"
  # end

  config.vm.provision "shell", path: "../src/install/packages.sh"
  config.vm.provision "shell", path: "../src/install/ansible.sh"
  config.vm.provision "shell", path: "../src/install/docker.sh"
  config.vm.provision "shell", path: "../src/install/vnc.sh"


end
