# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    
  # Configure the path below properly
  # change permissions accordingly as well
  config.vm.synced_folder "../../", "/vagrant", type: "virtualbox", mount_options: ["dmode=755,fmode=764"]

  config.ssh.insert_key = false

  config.vm.define "vm_python" do |node|
    node.vm.box = "devbox"
    node.vm.hostname = "pythonbox"
    node.vm.network "public_network"

    # Configure the ssh port on your machine as well
    node.vm.network "forwarded_port", guest: 22, id: "ssh", host: 2201

      ## Runtime Node
      node.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = 1*1024
        vb.cpus = 1
      end

      # use the code below if you need to add any package
      # through yum or pip
      
      # PRE_PROVISION_YUM_PACKAGE_LIST = [
      #   "sshpass"
      # ]
    
      # PRE_PROVISION_YUM_PACKAGE_LIST.each do |package|
      #   node.vm.provision "shell" do |s|
      #     s.inline = "sudo yum --nogpgcheck -y install $1"
      #     s.args = [package]
      #   end
      # end
    
      # PRE_PROVISION_PIP_PACKAGE_LIST = [
      #   #"docker-py",
      #   "ansible==2.9.14.0"
      # ]
    
      # PRE_PROVISION_PIP_PACKAGE_LIST.each do |package|
      #   node.vm.provision "shell" do |s|
      #     s.inline = "sudo pip install $1"
      #     s.args = [package]
      #   end
      # end
      

  end

  ssh_priv_key = File.read("./provisioners/keys/private_key")
  config.vm.provision 'shell', inline: "echo '#{ssh_priv_key}' > ~/.ssh/id_rsa_vagrant", privileged: false
  config.vm.provision 'shell', inline: "chmod 600 ~/.ssh/id_rsa_vagrant", privileged: false
  config.vm.provision 'shell', inline: "ssh-keygen -y -f ~/.ssh/id_rsa_vagrant >> ~/.ssh/authorized_keys", privileged: false
  
  #
  # you can use something like the code below to add some known hosts

  # etc_hosts = File.read("./provisioners/etc_hosts")
  # config.vm.provision 'shell', inline: "sudo echo '#{etc_hosts}' >> /etc/hosts", privileged: true

end
